name: macos 
on: [push]
jobs:
  check-bats-version:
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
            python3 -m pip install --upgrade pip
            pip3 install torch
            python3 test.py
