name: python_release
on: [push]
jobs:
  build_wheels:
    name: ${{ matrix.arch }} ${{ matrix.build }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-20.04, arch: x86_64,     build: 'cp*-manylinux*' }
          - { os: ubuntu-20.04, arch: x86_64,     build: 'cp*-musllinux*' }
          - { os: ubuntu-20.04, arch: x86_64,     build: 'pp*'            }
          - { os: ubuntu-20.04, arch: i686,       build: 'cp*-manylinux*' }
          - { os: ubuntu-20.04, arch: i686,       build: 'cp*-musllinux*' }
          - { os: ubuntu-20.04, arch: i686,       build: 'pp*'            }
          - { os: windows-2019, arch: x86,        build: 'cp*'            }
          - { os: windows-2019, arch: AMD64,      build: 'cp*'            }
          - { os: windows-2019, arch: AMD64,      build: 'pp*'            }
          - { os: windows-2019, arch: ARM64,      build: 'cp*'            }
          - { os: macos-11,     arch: x86_64,     build: 'cp*'            }
          - { os: macos-11,     arch: x86_64,     build: 'pp*'            }
          - { os: macos-11,     arch: arm64,      build: 'cp*'            }
          - { os: macos-11,     arch: universal2, build: 'cp*'            }

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: brew uninstall libomp
      if: matrix.os == 'macos-11'
      run: |
        brew uninstall --ignore-dependencies libomp
    - name: Build wheels
      uses: pypa/cibuildwheel@v2.11.4
      env:
        CIBW_ARCHS_MACOS: ${{ matrix.arch }}
        CIBW_ARCHS_LINUX: ${{ matrix.arch }}
        CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
        CIBW_BUILD: ${{ matrix.build }}
        CIBW_BUILD_VERBOSITY: 1
        CIBW_ENVIRONMENT: CMAKE_BUILD_PARALLEL_LEVEL=2

    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl