name: windows
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    env:
        TEST_NAME: foo
    steps:
      - name: test
        run: |
            echo $TEST_NAME
            mkdir $TEST_NAME
            ls
